# Generated by Django 2.2.5 on 2020-08-08 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_No', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cars/%Y/%m/%d')),
                ('available', models.BooleanField(default=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fine_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField()),
                ('has_paid', models.BooleanField(default=False)),
                ('has_returned', models.BooleanField(default=False)),
                ('customer_phone', models.CharField(max_length=10)),
                ('id_number', models.CharField(max_length=9, unique=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Station')),
            ],
        ),
    ]
