# Generated by Django 2.2.5 on 2020-08-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id_number',
            field=models.CharField(default=0, max_length=9),
        ),
    ]
