# Generated by Django 2.2.5 on 2020-08-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200808_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id_number',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
