# Generated by Django 2.2.5 on 2020-08-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200808_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='has_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
