# Generated by Django 2.2.5 on 2020-08-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_reservation_has_overdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='has_overdue',
        ),
        migrations.AlterField(
            model_name='station',
            name='county',
            field=models.CharField(help_text='Enter Name of the County First Letter should be CAPITAL while others Lower case', max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='town',
            field=models.CharField(help_text='Enter Name of the Town First Letter should be CAPITAL while others Lower case', max_length=100),
        ),
    ]
