# Generated by Django 2.2.5 on 2020-08-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20200812_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='county',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='town',
            field=models.CharField(choices=[('Thika', 'Thika'), ('Nyahururu', 'Nyahururu'), ('Limuru', 'Limuru'), ('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Kiambu', 'Kiambu'), ("Murang'a", "Murang'a"), ('Kerugoya', 'Kerugoya'), ('Kutus', 'Kutus'), ('Kagio', 'Kagio'), ('Meru', 'Meru'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Nyeri', 'Nyeri'), ('Karatina', 'Karatina'), ('Eldoret', 'Eldoret'), ('Narok', 'Narok'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii')], default='Thika', max_length=100),
        ),
    ]
